services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=book_db'
      - 'POSTGRES_PASSWORD=optimusmac'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432'
  redis:
    image: 'redis:latest'
    ports:
      - '6379'
