spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book_db
    username: postgres
    password: optimusmac
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  application:
    name: BookBuddy
  redis:
    host: localhost
    port: 6379
  mail:
    host: smtp.mail.ru
    port: 587
    username: jormo2@mail.ru
    password: F7Qk8BGYNmMuKtXjPyAP
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
image:
  upload-dir: src/main/resources/static